
name = "Guilherme Fuentes"
downloads-dir = "~/Downloads"
default-page-size = 50
signature = """
Atenciosamente,
Guilherme Fuentes
"""
watch-cmds=["notify-send 'E-mail novo!'"]
notify-cmd = "~/.config/scripts/notify-himalaya.sh"
notify-query="not seen"

[gmail]
default = true
email = "guifuentes8@gmail.com"

smtp-host = "smtp.gmail.com"
smtp-port = 465
smtp-login = "guifuentes8@gmail.com"
smtp-passwd-cmd = "echo vrbaryplulttizlj"

imap-host = "imap.gmail.com"
imap-port = 993
imap-login = "guifuentes8@gmail.com"
imap-passwd-cmd = "echo vrbaryplulttizlj"

[gmail.mailboxes]
sent = "[Gmail]/Sent Mail"
draft = "[Gmail]/Drafts"
