{ pkgs, ... }:
{
  environment.systemPackages = (with pkgs.gnomeExtensions; [
    appindicator
    burn-my-windows
    caffeine
    clipboard-history
    color-picker
    color-app-menu-icon-for-gnome-40
    docker
    emoji-selector
    force-quit
    gnome-40-ui-improvements
    gsconnect
    lock-keys
    middle-click-to-close-in-overview
    muteunmute
    notification-timeout
    noannoyance-2
    remove-alttab-delay-v2
    replace-activities-text
    show-desktop-button
    tactile
    task-widget
    user-avatar-in-quick-settings
    vitals
    wayland-or-x11
    window-is-ready-remover
  ]);
}
