#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d    阮 輸   聆 
bspc config border_width         4
bspc config window_gap          12

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

bspc config normal_border_color "#bd93f9"
bspc config focused_border_color "#50fa7b"
bspc config urgent_border_color "#ff5555"
bspc config presel_border_color "#26E2FF"

# autostart

picom -b --experimental-backends --backend glx
nitrogen --restore
setxkbmap -model abnt2 -layout br -variant abnt2
~/.config/polybar/launch.sh
/usr/bin/numlockx on
