cookie: sp_t=363fbc8b7c74e8ea8effd15395c757fe; sp_landing=https://open.spotify.com/?sp_cid=363fbc8b7c74e8ea8effd15395c757fe&device=desktop;
  _gid=GA1.2.779718061.1657858317; sp_adid=adfb6ec4-f5c8-44ac-8cd6-724e5d5d909a; _gcl_au=1.1.967346680.1657859748;
  sss=1; _gat_UA-5784146-31=1; _fbp=fb.1.1657859748576.1951698478; _gat=1; sp_dc=AQDYh5SqftYCJb49wi35MWQnp55C1zFIz9quoPapaF4WkgTyi9_UqMT26-Jl_utwkvbUEx9MWtp3P8q6jGy4QzBEWMc-k86OOBpLUFjhluXjxSovjVQ2QZ1r5cRmL36fADVJPBno0l5Ihdj1Tg54da_qX0o7YF4H;
  sp_key=cbca99dc-9fcb-42fa-abdc-2191f21d982e; ki_t=1657859749113;1657859749113;1657859758209;1;2;
  ki_r=aHR0cHM6Ly9hY2NvdW50cy5zcG90aWZ5LmNvbS8=; _ga_ZWG1NSHWD8=GS1.1.1657859748.1.1.1657859758.0;
  _ga=GA1.1.2117438379.1657858317; OptanonConsent=isIABGlobal=false&datestamp=Fri+Jul+15+2022+01:35:58+GMT-0300+(Brasilia+Standard+Time)&version=6.26.0&hosts=&landingPath=NotLandingPage&groups=s00:1,f00:1,m00:1,t00:1,i00:1,f02:1,m02:1,t02:1&AwaitingReconsent=false
player: spotify
timerInterval: 200
updateInterval: 2000
style:
  hAlignment: center
  before:
    background: ""
    foreground: ""
    bold: true
    italic: false
    undeline: false
    strikethrough: false
    blink: false
    faint: false
  current:
    background: ""
    foreground: ""
    bold: true
    italic: false
    undeline: false
    strikethrough: false
    blink: false
    faint: false
  after:
    background: ""
    foreground: ""
    bold: false
    italic: false
    undeline: false
    strikethrough: false
    blink: false
    faint: true
pipe:
  length: 0
  overflow: word
  ignoreErrors: true
mpd:
  address: 127.0.0.1:6600
  password: ""
mopidy:
  address: 127.0.0.1:6680
