theme = "dracula"
client_id = "2c4e2f8284664d6688a206df92bf7d8b"
app_refresh_duration_in_ms = 32
playback_refresh_duration_in_ms = 0
cover_image_refresh_duration_in_ms = 2000
track_table_item_max_len = 60
enable_media_control = true
default_device = "spotify-player"
#cover_image_length = 9
#cover_image_width = 9

[device]
name = "spotify-player"
device_type = "speaker"
volume = 85
bitrate = 320
audio_cache = true
